### ISSUE TITLE
(SURE-2565) Support for managed identity in AKS

### ISSUE THREAD

**Issue by kkaempf** [rancher/aks-operator#103]
https://jira.suse.com/browse/SURE-2565
https://github.com/rancher/rancher/issues/27559

**Comment by cpinjani** [comment]
Validated on build: `v2.8-7113f094007e3105a906b414fe18ee370c77bb5e-head`

As stated in issue description and reported version v2.4 - "_The UI presents mandatory fields to enter the SP for AKS; I propose to add a ratio button where the user can select to create a MI instead._"

Rancher v2.4:
![image](https://github.com/rancher/aks-operator/assets/73099870/fcc0e5ce-5828-4436-be39-c27804bf9de3)

However, we still use service principal for AKS clusters (https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/aks#prerequisites-in-microsoft-azure)
![image](https://github.com/rancher/aks-operator/assets/73099870/87871039-7e7f-4a41-b0a4-b9892accd5e7)

@kkaempf @davidstauffer Please review this, as support for it is not added yet.

**Comment by cpinjani** [comment]
Moving to Backlog, cc: @mjura

**Comment by yiannistri** [comment]
Upon investigation, it seems that the `aks-operator` already creates clusters using managed identities. After a cluster gets provisioned from Rancher, the following command can be used to determine what type of managed identity the cluster is using ([source](https://learn.microsoft.com/en-us/azure/aks/use-managed-identity#determine-which-type-of-managed-identity-a-cluster-is-using)): 
```
az aks show --name myAKSCluster --resource-group myResourceGroup --query identity.type --output tsv
```
It is also indicated in the Azure Portal by accessing the `Managed Identities` service. There should be a managed identity associated with the cluster's node pool.

There are two types of managed identities ([source](https://learn.microsoft.com/en-us/azure/aks/use-managed-identity#overview)): system-assigned and user-assigned. The CRD used by the `aks-operator` allows users to creates clusters with either type, see below for examples.

Cluster using system-assigned managed identity
```
apiVersion: aks.cattle.io/v1
kind: AKSClusterConfig
metadata:
  name: myAKSCluster
  namespace: cattle-global-data
spec:
  azureCredentialSecret:  cattle-global-data:cc-abcde
  clusterName: myAKSCluster
  dnsPrefix: myAKSCluster
  managedIdentity: true # also true if field is omitted and aks-operator detects a tenantId
  imported: false
  kubernetesVersion: 1.30.3
  linuxAdminUsername: azureuser
  loadBalancerSku: Standard
  networkPlugin: kubenet
  nodePools:
  - availabilityZones:
    - "1"
    count: 1
    enableAutoScaling: false
    maxPods: 110
    mode: System
    name: agentpool
    orchestratorVersion: 1.30.3
    osDiskSizeGB: 30
    osDiskType: Managed
    osType: Linux
    vmSize: Standard_B4ms
  privateCluster: false
  resourceLocation: eastus
  resourceGroup: myResourceGroup
```

Cluster using user-assigned managed identity
```
apiVersion: aks.cattle.io/v1
kind: AKSClusterConfig
metadata:
  name: myAKSCluster
  namespace: cattle-global-data
spec:
  azureCredentialSecret:  cattle-global-data:cc-abcde
  clusterName: myAKSCluster
  dnsPrefix: myAKSCluster
  userAssignedIdentity: '/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/myResourceGroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity1'
  imported: false
  kubernetesVersion: 1.30.3
  linuxAdminUsername: azureuser
  loadBalancerSku: Standard
  networkPlugin: kubenet
  nodePools:
  - availabilityZones:
    - "1"
    count: 1
    enableAutoScaling: false
    maxPods: 110
    mode: System
    name: agentpool
    orchestratorVersion: 1.30.3
    osDiskSizeGB: 30
    osDiskType: Managed
    osType: Linux
    vmSize: Standard_B4ms
  privateCluster: false
  resourceLocation: eastus
  resourceGroup: myResourceGroup
``` 
Note that when using user-assigned identity, the identity needs to have been created prior to creating the cluster. Also these fields are used during cluster creation only.

While looking into this, I came across an issue with user-assigned managed identities not being associated correctly to node pools, at least the association is not shown in the Azure portal as it is shown for system-assigned managed identities. Not sure if we prefer to close this one and open a new issue though cc @kkaempf @cpinjani
