### ISSUE TITLE
[SURE-3400 related] Outbound type is restored to LoadBalancer if UserDefinedRouting is selected

### ISSUE THREAD

**Issue by valaparthvi** [rancher/aks-operator#750]
If an AKS cluster is created with an outbound type: userdefinedrouting, it is restored to LoadBalancer after the cluster is provisioned successfully. This change appears to be triggered from Azure console, because the change appears in UpstreamSpec first and then in AKSConfig.

The same was reproduced when I provisioned AKS via Terraform, ref: https://github.com/rancher/aks-operator/issues/709.

Rancher version: v2.10-c4944b3ca0b39c474121df9e7ef31f7aff4e4f7a-head.
AKS Operator version: rancher-aks-operator:105.1.0+up1.10.1-rc.2

**PR's:**
- [ ] https://github.com/rancher/aks-operator/pull/776
- [ ] https://github.com/rancher/aks-operator/pull/777
- [ ] https://github.com/rancher/aks-operator/pull/788

**Comment by mjura** [comment]
@mantis-toboggan-md Rancher UI needs to be also fixed

![Image](https://github.com/user-attachments/assets/fd168efe-ff60-418a-abe8-f83b123705e4)

1. Box name where users are selecting LoadBalancer or User Defined Routing needs to be called Outbound Type, currently is DNS Prefix
2. When User Defined Routing is selected then Virtual Network has to be provided, it can't be empty
3. When User Defined Routing is selected then Network Plugin Azure CNI has to be selected

**Comment by kkaempf** [comment]
PRs got all merged, moving to "To Test"

**Comment by valaparthvi** [comment]
Tested this on v2.10-d352f3ad3f7dec680c91e8bf7d5c87574f2ece2a-head, and it appears to have been fixed.
- Returned error when Azure CNI was not selected
- Returned error when subnet was not selected.
- Successfully provisioned a cluster to use UserDefinedRouting, thanks to @cpinjani for verifying this case 🙌

**Comment by valaparthvi** [comment]
Works on v2.9-023781e52103c45a9bbdf3cb47d60b9336321daa-head.

**Comment by valaparthvi** [comment]
I was too quick in testing 2.9. It is not fixed on 2.9.
- No error was thrown on not using Azure CNI
- UserDefinedRouting was reverted back to LoadBalancer.

**Comment by valaparthvi** [comment]
@cpinjani tried testing this on 2.9 and the issue seems to have been fixed, it seems I was not using `stgregistry` which is why it did not work. Closing the issue.

**Comment by cpinjani** [comment]
Tested on `v2.9-dde222feabec581e9f15256620a27a47a2e630a2-head, aks-operator:v1.9.6-rc.10`
Cluster spec for provisioned cluster:

```
aksConfig:
    authBaseUrl: null
    authorizedIpRanges: null
    azureCredentialSecret: cattle-global-data:cc-2r9s2
    baseUrl: null
    clusterName: cpinjani-udr
    dnsPrefix: cpinjani-udr
    dnsServiceIp: 10.1.0.10
    dockerBridgeCidr: null
    httpApplicationRouting: null
    imported: false
    kubernetesVersion: 1.30.4
    linuxAdminUsername: azureuser
    loadBalancerSku: standard
    logAnalyticsWorkspaceGroup: null
    logAnalyticsWorkspaceName: null
    managedIdentity: null
    monitoring: null
    networkPlugin: azure
    networkPolicy: azure
    nodePools:
      - availabilityZones:
          - '1'
          - '2'
          - '3'
        count: 1
        maxPods: 110
        maxSurge: '1'
        mode: System
        name: agentpool
        orchestratorVersion: 1.30.4
        osDiskSizeGB: 128
        osDiskType: Managed
        osType: Linux
        vmSize: Standard_DS2_v2
        vnetSubnetID: >-
          /subscriptions/<REDACTED>/resourceGroups/<REDACTED>/providers/Microsoft.Network/virtualNetworks/<REDACTED>/subnets/aks-subnet
    outboundType: userDefinedRouting
    podCidr: null
    privateCluster: false
    privateDnsZone: null
    resourceGroup: <REDACTED>
    resourceLocation: eastus
    serviceCidr: 10.1.0.0/16
    subnet: null
    tags:
      Team: container-es
    userAssignedIdentity: null
    virtualNetwork: null
    virtualNetworkResourceGroup: null
```
