### ISSUE TITLE
(SURE-5538) PV is not having CSI driver as vol plugin which is current default for latest versions of AKS

### ISSUE THREAD

**Issue by kkaempf** [rancher/aks-operator#96]
https://jira.suse.com/browse/SURE-5538

**Comment by mjura** [comment]
It is more feature request to Rancher UI


![Image](https://user-images.githubusercontent.com/4455471/236228066-9d6199cc-0ee3-4f24-ac93-eeffbc711f11.png)

**Comment by mjura** [comment]
Here it needs to be added 

Azure Disk CSI
 - Volume Handle
 - Volume Attributes
   - fsType

Example template:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  name: pv-azuredisk
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/<subscriptionID>/resourceGroups/MC_myAKSCluster_myAKSCluster_eastus/providers/Microsoft.Compute/di
sks/myAKSDisk
    volumeAttributes:
      fsType: ext4
```

https://learn.microsoft.com/en-us/azure/aks/azure-csi-disk-storage-provision#static-provisioning-parameters

**Comment by mjura** [comment]
Azure Filesystem CSI
 - Share Name
 - Resource Group
 - Secret Name
 - Volume Handle
 - Mount Options

```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: azurefile
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: unique-volumeid  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      resourceGroup: resourceGroupName  # optional, only set this when storage account is not in the same resource group as node
      shareName: aksshare
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl
```
https://learn.microsoft.com/en-us/azure/aks/azure-csi-files-storage-provision#static-provisioning-parameters
